export type VocabularyType = NounDec | AdjDec | AdjSuffix | Prefix | GreekPreSuff | GreekLatin | Misc;

//parser: data.replaceAll(",\n-",",-").split("\n").map(v=>console.log(v)||v.match(/(.*?),\s*(.*?),\s*(.)\s*(.*)/).splice(1,4)).map(([a,b,c,d])=>({dkl:"a",vocN:a,vocG:b,gen:c,deu:d}))
type NounDec = {
    typ: "N";
    dkl: "a" | "o" | "k" | "i" | "u" | "e" | "uS" | "iS";
    vocN: string;
    vocG: string;
    vocNP?: string;
    vocGP?: string;
    gen: "m" | "n" | "f";
    deu: string;
};
type AdjDec = { typ: "A"; dkl: "ao" | "k" | "i"; vocM: string; vocF?: string; vocN?: string; vocG?: string; deu: string };
type AdjSuffix = { typ: "aS"; voc: string; deu: string; bsp: string };
type Prefix = { typ: "P"; voc: string; deu: string };
type GreekPreSuff = { typ: "G"; voc: string; deu: string };
type GreekLatin = { typ: "GL"; vocG: string; vocL: string; deu: string };
type Misc = { typ: "M"; voc: string; deu: string };

const getANomSg = (v: NounDec) => v.vocN;
const getAGenSg = (v: NounDec) => v.vocN.slice(0, -1) + "ae";
const getANomPl = (v: NounDec) => v.vocN.slice(0, -1) + "ae";
const getAGenPl = (v: NounDec) => v.vocN.slice(0, -1) + "arum";

const getONomSg = (v: NounDec) => v.vocN;
const getOGenSg = (v: NounDec) => v.vocN.slice(0, -2) + "i";
const getONomPl = (v: NounDec) => v.vocN.slice(0, -2) + (v.gen == "m" ? "i" : "a");
const getOGenPl = (v: NounDec) => v.vocN.slice(0, -2) + "orum";

const getKNomSg = (v: NounDec) => v.vocN;
const getKGenSg = (v: NounDec) => v.vocG;
const getKNomPl = (v: NounDec) => v.vocG.slice(0, -2) + (v.gen != "n" ? "es" : "a");
const getKGenPl = (v: NounDec) => v.vocG.slice(0, -2) + "um";

const getSNomSg = (v: NounDec) => v.vocN;
const getSGenSg = (v: NounDec) => v.vocG;
const getSNomPl = (v: NounDec) => v.vocNP;
const getSGenPl = (v: NounDec) => v.vocGP;

const getINomSg = (v: NounDec) => v.vocN;
const getIGenSg = (v: NounDec) => v.vocG;
const getINomPl = (v: NounDec) => v.vocG.slice(0, -2) + (v.gen != "n" ? "es" : "ia");
const getIGenPl = (v: NounDec) => v.vocG.slice(0, -2) + "ium";

const getUNomSg = (v: NounDec) => v.vocN;
const getUGenSg = (v: NounDec) => (v.gen != "n" ? v.vocN.slice(0, -2) : v.vocN.slice(0, -1)) + "us";
const getUNomPl = (v: NounDec) => (v.gen != "n" ? v.vocN.slice(0, -2) + "ūs" : v.vocN.slice(0, -1) + "ua");
const getUGenPl = (v: NounDec) => (v.gen != "n" ? v.vocN.slice(0, -2) : v.vocN.slice(0, -1)) + "uum";

const getENomSg = (v: NounDec) => v.vocN;
const getEGenSg = (v: NounDec) => v.vocG;
const getENomPl = (v: NounDec) => v.vocG.slice(0, -2) + "es";
const getEGenPl = (v: NounDec) => v.vocG.slice(0, -2) + "erum";

const getAONomSgA = (v: AdjDec, g: "m" | "f" | "n") => v.vocM.slice(0, -2) + (g == "m" ? "us" : g == "f" ? "a" : "um");
const getAOGenSgA = (v: AdjDec, g: "m" | "f" | "n") => v.vocM.slice(0, -2) + (g == "m" ? "i" : g == "f" ? "ae" : "i");
const getAONomPlA = (v: AdjDec, g: "m" | "f" | "n") => v.vocM.slice(0, -2) + (g == "m" ? "i" : g == "f" ? "ae" : "a");
const getAOGenPlA = (v: AdjDec, g: "m" | "f" | "n") => v.vocM.slice(0, -2) + (g == "m" ? "orum" : g == "f" ? "arum" : "orum");

const getKNomSgA = (v: AdjDec, g: "m" | "f" | "n") => (g != "n" || !v.vocN ? v.vocM : v.vocN);
const getKGenSgA = (v: AdjDec, g: "m" | "f" | "n") => v.vocG;
const getKNomPlA = (v: AdjDec, g: "m" | "f" | "n") => v.vocG?.slice(0, -2) + (g != "n" ? "es" : "ia");
const getKGenPlA = (v: AdjDec, g: "m" | "f" | "n") => v.vocG?.slice(0, -2) + "ium";

const getINomSgA = (v: AdjDec, g: "m" | "f" | "n") => (g != "n" || !v.vocN ? v.vocM : v.vocM?.slice(0, -2) + "e");
const getIGenSgA = (v: AdjDec, g: "m" | "f" | "n") => (v.vocG || v.vocM).slice(0, -2) + "is";
const getINomPlA = (v: AdjDec, g: "m" | "f" | "n") => (v.vocG || v.vocM).slice(0, -2) + (g != "n" ? "es" : "ia");
const getIGenPlA = (v: AdjDec, g: "m" | "f" | "n") => (v.vocG || v.vocM).slice(0, -2) + "ium";

const getDecA = (v: NounDec) => [getANomSg(v), getAGenSg(v), getANomPl(v), getAGenPl(v)];
const getDecO = (v: NounDec) => [getONomSg(v), getOGenSg(v), getONomPl(v), getOGenPl(v)];
const getDecK = (v: NounDec) => [getKNomSg(v), getKGenSg(v), getKNomPl(v), getKGenPl(v)];
const getDecS = (v: NounDec) => [getSNomSg(v), getSGenSg(v), getSNomPl(v), getSGenPl(v)];
const getDecI = (v: NounDec) => [getINomSg(v), getIGenSg(v), getINomPl(v), getIGenPl(v)];
const getDecU = (v: NounDec) => [getUNomSg(v), getUGenSg(v), getUNomPl(v), getUGenPl(v)];
const getDecE = (v: NounDec) => [getENomSg(v), getEGenSg(v), getENomPl(v), getEGenPl(v)];

const getDecAOA = (v: AdjDec, g: "m" | "f" | "n") => [getAONomSgA(v, g), getAOGenSgA(v, g), getAONomPlA(v, g), getAOGenPlA(v, g)];
const getDecKA = (v: AdjDec, g: "m" | "f" | "n") => [getKNomSgA(v, g), getKGenSgA(v, g), getKNomPlA(v, g), getKGenPlA(v, g)];
const getDecIA = (v: AdjDec, g: "m" | "f" | "n") => [getINomSgA(v, g), getIGenSgA(v, g), getINomPlA(v, g), getIGenPlA(v, g)];

export const getNounDec = (v: NounDec) => {
    if (v.dkl == "a") return getDecA(v);
    if (v.dkl == "o") return getDecO(v);
    if (v.dkl == "k") return getDecK(v);
    if (v.dkl == "uS") return getDecS(v);
    if (v.dkl == "iS") return getDecS(v);
    if (v.dkl == "i") return getDecI(v);
    if (v.dkl == "u") return getDecU(v);
    if (v.dkl == "e") return getDecE(v);
};
export const getAdjDec = (v: AdjDec) => {
    if (v.dkl == "ao") return [getDecAOA(v, "m"), getDecAOA(v, "f"), getDecAOA(v, "n")];
    if (v.dkl == "k") return [getDecKA(v, "m"), getDecKA(v, "f"), getDecKA(v, "n")];
    if (v.dkl == "i") return [getDecIA(v, "m"), getDecIA(v, "f"), getDecIA(v, "n")];
};

const data: VocabularyType[] = [
    { typ: "N", dkl: "a", vocN: "ala", vocG: "-ae", gen: "f", deu: "der Flügel" },
    { typ: "N", dkl: "a", vocN: "ampulla", vocG: "-ae", gen: "f", deu: "das kleine Gefäß" },
    { typ: "N", dkl: "a", vocN: "angina", vocG: "-ae", gen: "f", deu: "die Enge" },
    { typ: "N", dkl: "a", vocN: "aorta", vocG: "-ae", gen: "f", deu: "die Schlagader" },
    { typ: "N", dkl: "a", vocN: "apertura", vocG: "-ae", gen: "f", deu: "die Öffnung" },
    { typ: "N", dkl: "a", vocN: "aqua", vocG: "-ae", gen: "f", deu: "das Wasser" },
    { typ: "N", dkl: "a", vocN: "area", vocG: "-ae", gen: "f", deu: "die Fläche" },
    { typ: "N", dkl: "a", vocN: "arteria", vocG: "-ae", gen: "f", deu: "die Schlagader" },
    { typ: "N", dkl: "a", vocN: "auricula", vocG: "-ae", gen: "f", deu: "das Öhrchen" },
    { typ: "N", dkl: "a", vocN: "axilla", vocG: "-ae", gen: "f", deu: "die Achsel(höhle)" },
    { typ: "N", dkl: "a", vocN: "bucca", vocG: "-ae", gen: "f", deu: "die Backe" },
    { typ: "N", dkl: "a", vocN: "bulla", vocG: "-ae", gen: "f", deu: "die Blase" },
    { typ: "N", dkl: "a", vocN: "bursa", vocG: "-ae", gen: "f", deu: "die Tasche, der Beutel (Gewebstasche, Schleimbeutel)" },
    { typ: "N", dkl: "a", vocN: "cauda", vocG: "-ae", gen: "f", deu: "der Schwanz, das Endstück eines Organs" },
    { typ: "N", dkl: "a", vocN: "cardia", vocG: "-ae", gen: "f", deu: "das Herz; der Mageneingang" },
    { typ: "N", dkl: "a", vocN: "cellula", vocG: "-ae", gen: "f", deu: "die kleine Kammer, die Zelle" },
    { typ: "N", dkl: "a", vocN: "choana", vocG: "-ae", gen: "f", deu: "die hintere Nasenöffnung" },
    { typ: "N", dkl: "a", vocN: "chorda", vocG: "-ae", gen: "f", deu: "der Strang, die Saite" },
    { typ: "N", dkl: "a", vocN: "circumferentia", vocG: "-ae", gen: "f", deu: "der Umfang" },
    { typ: "N", dkl: "a", vocN: "cisterna", vocG: "-ae", gen: "f", deu: "die Zisterne; der Hohlraum" },
    { typ: "N", dkl: "a", vocN: "clavicula", vocG: "-ae", gen: "f", deu: "das Schlüsselbein" },
    { typ: "N", dkl: "a", vocN: "cochlea", vocG: "-ae", gen: "f", deu: "die Schnecke" },
    { typ: "N", dkl: "a", vocN: "collega", vocG: "-ae", gen: "m", deu: "der Kollege" },
    { typ: "N", dkl: "a", vocN: "columna", vocG: "-ae", gen: "f", deu: "die Säule" },
    { typ: "N", dkl: "a", vocN: "commissura", vocG: "-ae", gen: "f", deu: "die Zusammenfügung, die Verbindung" },
    { typ: "N", dkl: "a", vocN: "concha", vocG: "-ae", gen: "f", deu: "die Muschel" },
    { typ: "N", dkl: "a", vocN: "cornea", vocG: "-ae", gen: "f", deu: "die Hornhaut" },
    { typ: "N", dkl: "a", vocN: "corona", vocG: "-ae", gen: "f", deu: "die Krone" },
    { typ: "N", dkl: "a", vocN: "costa", vocG: "-ae", gen: "f", deu: "die Rippe" },
    { typ: "N", dkl: "a", vocN: "coxa", vocG: "-ae", gen: "f", deu: "die Hüfte" },
    { typ: "N", dkl: "a", vocN: "crista", vocG: "-ae", gen: "f", deu: "der Kamm, die Leiste" },
    { typ: "N", dkl: "a", vocN: "eminentia", vocG: "-ae", gen: "f", deu: "die Vorwölbung" },
    { typ: "N", dkl: "a", vocN: "fascia", vocG: "-ae", gen: "f", deu: "die Faszie, die Bindegewebshülle" },
    { typ: "N", dkl: "a", vocN: "fibra", vocG: "-ae", gen: "f", deu: "die Faser" },
    { typ: "N", dkl: "a", vocN: "fibula", vocG: "-ae", gen: "f", deu: "das Wadenbein" },
    { typ: "N", dkl: "a", vocN: "fissura", vocG: "-ae", gen: "f", deu: "die Spalte" },
    { typ: "N", dkl: "a", vocN: "fossa", vocG: "-ae", gen: "f", deu: "der Graben" },
    { typ: "N", dkl: "a", vocN: "fovea", vocG: "-ae", gen: "f", deu: "die Grube" },
    { typ: "N", dkl: "a", vocN: "fractura", vocG: "-ae", gen: "f", deu: "der Bruch" },
    { typ: "N", dkl: "a", vocN: "gingiva", vocG: "-ae", gen: "f", deu: "das Zahnfleisch" },
    { typ: "N", dkl: "a", vocN: "glandula", vocG: "-ae", gen: "f", deu: "die (kleine) Drüse" },
    { typ: "N", dkl: "a", vocN: "glossa", vocG: "-ae", gen: "f", deu: "die Zunge; die Sprache" },
    { typ: "N", dkl: "a", vocN: "hernia", vocG: "-ae", gen: "f", deu: "der Bruch" },
    { typ: "N", dkl: "a", vocN: "incisura", vocG: "-ae", gen: "f", deu: "der Einschnitt, die Einbuchtung" },
    { typ: "N", dkl: "a", vocN: "insufficientia", vocG: "-ae", gen: "f", deu: "die ungenügende Leistung" },
    { typ: "N", dkl: "a", vocN: "lamina", vocG: "-ae", gen: "f", deu: "die Schicht" },
    { typ: "N", dkl: "a", vocN: "linea", vocG: "-ae", gen: "f", deu: "die Linie" },
    { typ: "N", dkl: "a", vocN: "lingua", vocG: "-ae", gen: "f", deu: "die Zunge, die Sprache" },
    { typ: "N", dkl: "a", vocN: "mamma", vocG: "-ae", gen: "f", deu: "die Brust" },
    { typ: "N", dkl: "a", vocN: "mammilla ", vocG: "-ae", gen: "f", deu: "die Brustwarze" },
    { typ: "N", dkl: "a", vocN: "mandibula", vocG: "-ae", gen: "f", deu: "der Unterkiefer" },
    { typ: "N", dkl: "a", vocN: "materia", vocG: "-ae", gen: "f", deu: "der Stoff, das Material" },
    { typ: "N", dkl: "a", vocN: "maxilla", vocG: "-ae", gen: "f", deu: "der Oberkiefer" },
    { typ: "N", dkl: "a", vocN: "medulla", vocG: "-ae", gen: "f", deu: "das Mark" },
    { typ: "N", dkl: "a", vocN: "membrana", vocG: "-ae", gen: "f", deu: "die Membran, die Haut" },
    { typ: "N", dkl: "a", vocN: "natura", vocG: "-ae", gen: "f", deu: "die Natur, das Wesen" },
    { typ: "N", dkl: "a", vocN: "noxa", vocG: "-ae", gen: "f", deu: "der Schaden, der Schadstoff" },
    { typ: "N", dkl: "a", vocN: "orbita", vocG: "-ae", gen: "f", deu: "die Augenhöhle" },
    { typ: "N", dkl: "a", vocN: "palma", vocG: "-ae", gen: "f", deu: "die Handfläche" },
    { typ: "N", dkl: "a", vocN: "palpebra", vocG: "-ae", gen: "f", deu: "das Lid" },
    { typ: "N", dkl: "a", vocN: "patella", vocG: "-ae", gen: "f", deu: "die Kniescheibe" },
    { typ: "N", dkl: "a", vocN: "pellicula", vocG: "-ae", gen: "f", deu: "das Schmelzoberhäutchen" },
    { typ: "N", dkl: "a", vocN: "pleura", vocG: "-ae", gen: "f", deu: "das Brustfell" },
    { typ: "N", dkl: "a", vocN: "plica", vocG: "-ae", gen: "f", deu: "die Falte" },
    { typ: "N", dkl: "a", vocN: "porta", vocG: "-ae", gen: "f", deu: "die Pforte" },
    { typ: "N", dkl: "a", vocN: "pulpa", vocG: "-ae", gen: "f", deu: "das Fleischige, das Mark" },
    { typ: "N", dkl: "a", vocN: "retina", vocG: "-ae", gen: "f", deu: "die Netzhaut des Auges" },
    { typ: "N", dkl: "a", vocN: "rima", vocG: "-ae", gen: "f", deu: "die Spalte" },
    { typ: "N", dkl: "a", vocN: "scapula", vocG: "-ae", gen: "f", deu: "das Schulterblatt" },
    { typ: "N", dkl: "a", vocN: "sella", vocG: "-ae", gen: "f", deu: "der Sattel" },
    { typ: "N", dkl: "a", vocN: "spina", vocG: "-ae", gen: "f", deu: "der Dorn" },
    { typ: "N", dkl: "a", vocN: "substantia", vocG: "-ae", gen: "f", deu: "die Substanz" },
    { typ: "N", dkl: "a", vocN: "sutura", vocG: "-ae", gen: "f", deu: "die Naht" },
    { typ: "N", dkl: "a", vocN: "synovia", vocG: "-ae", gen: "f", deu: "die Gelenkschmiere" },
    { typ: "N", dkl: "a", vocN: "taenia", vocG: "-ae", gen: "f", deu: "das Band; der Bandwurm" },
    { typ: "N", dkl: "a", vocN: "tela", vocG: "-ae", gen: "f", deu: "das Gewebe, die Gewebsschicht" },
    { typ: "N", dkl: "a", vocN: "tibia", vocG: "-ae", gen: "f", deu: "das Schienbein" },
    { typ: "N", dkl: "a", vocN: "trachea", vocG: "-ae", gen: "f", deu: "die Luftröhre" },
    { typ: "N", dkl: "a", vocN: "trochlea", vocG: "-ae", gen: "f", deu: "die Rolle" },
    { typ: "N", dkl: "a", vocN: "tuba", vocG: "-ae", gen: "f", deu: "die Trompete, die Tube" },
    { typ: "N", dkl: "a", vocN: "tunica", vocG: "-ae", gen: "f", deu: "die Hülle, die Gewebsschicht" },
    { typ: "N", dkl: "a", vocN: "ulna", vocG: "-ae", gen: "f", deu: "die Elle" },
    { typ: "N", dkl: "a", vocN: "urethra", vocG: "-ae", gen: "f", deu: "die Harnröhre" },
    { typ: "N", dkl: "a", vocN: "uvula", vocG: "-ae", gen: "f", deu: "die kleine Traube, das Zäpfchen" },
    { typ: "N", dkl: "a", vocN: "vagina", vocG: "-ae", gen: "f", deu: "die Hülle, die Scheide" },
    { typ: "N", dkl: "a", vocN: "valva", vocG: "-ae", gen: "f", deu: "die Klappe" },
    { typ: "N", dkl: "a", vocN: "vena", vocG: "-ae", gen: "f", deu: "die Vene" },
    { typ: "N", dkl: "a", vocN: "vertebra", vocG: "-ae", gen: "f", deu: "der Wirbel" },
    { typ: "N", dkl: "a", vocN: "vesica", vocG: "-ae", gen: "f", deu: "die Blase" },
    { typ: "N", dkl: "a", vocN: "zonula", vocG: "-ae", gen: "f", deu: "das Gürtelchen" },
    { typ: "N", dkl: "o", vocN: "acetabulum", vocG: "-i", gen: "n", deu: "die Schale, die Hüftpfanne" },
    { typ: "N", dkl: "o", vocN: "acromion", vocG: "-i", gen: "n", deu: "die Schulterhöhe" },
    { typ: "N", dkl: "o", vocN: "amnion", vocG: "-i", gen: "n", deu: "die innere Eihaut" },
    { typ: "N", dkl: "o", vocN: "angulus", vocG: "-i", gen: "m", deu: "der Winkel" },
    { typ: "N", dkl: "o", vocN: "antebrachium", vocG: "-i", gen: "n", deu: "der Unterarm" },
    { typ: "N", dkl: "o", vocN: "antrum", vocG: "-i", gen: "n", deu: "die Höhle" },
    { typ: "N", dkl: "o", vocN: "anulus", vocG: "-i", gen: "m", deu: "der (kleine) Ring" },
    { typ: "N", dkl: "o", vocN: "anus", vocG: "-i", gen: "m", deu: "der Ring, der After" },
    { typ: "N", dkl: "o", vocN: "atrium", vocG: "-i", gen: "n", deu: "der Vorhof" },
    { typ: "N", dkl: "o", vocN: "bacillus", vocG: "-i", gen: "m", deu: "das Stäbchen" },
    { typ: "N", dkl: "o", vocN: "brachium", vocG: "-i", gen: "n", deu: "der (Ober)arm" },
    { typ: "N", dkl: "o", vocN: "bronchus", vocG: "-i", gen: "m", deu: "der Ast der Luftröhre" },
    { typ: "N", dkl: "o", vocN: "bulbus", vocG: "-i", gen: "m", deu: "die Zwiebel; die Kugel" },
    { typ: "N", dkl: "o", vocN: "caecum", vocG: "-i", gen: "n", deu: "der Blinddarm" },
    { typ: "N", dkl: "o", vocN: "cancer", vocG: "cancri", gen: "m", deu: "der Krebs" },
    { typ: "N", dkl: "o", vocN: "capitulum", vocG: "-i", gen: "n", deu: "das Köpfchen" },
    { typ: "N", dkl: "o", vocN: "carpus", vocG: "-i", gen: "m", deu: "die Handwurzel" },
    { typ: "N", dkl: "o", vocN: "cavum", vocG: "-i", gen: "n", deu: "die Höhle, der Hohlraum" },
    { typ: "N", dkl: "o", vocN: "cementum", vocG: "-i", gen: "n", deu: "das Zement" },
    { typ: "N", dkl: "o", vocN: "cerebellum", vocG: "-i", gen: "n", deu: "das Kleinhirn" },
    { typ: "N", dkl: "o", vocN: "cerebrum", vocG: "-i", gen: "n", deu: "das Gehirn" },
    { typ: "N", dkl: "o", vocN: "chorion", vocG: "-i", gen: "n", deu: "die Zottenhaut" },
    { typ: "N", dkl: "o", vocN: "cilium", vocG: "-i", gen: "n", deu: "die Wimper, das Augenlid" },
    { typ: "N", dkl: "o", vocN: "circulus", vocG: "-i", gen: "m", deu: "der Kreis" },
    { typ: "N", dkl: "o", vocN: "claustrum", vocG: "-i", gen: "n", deu: "der Verschluss" },
    { typ: "N", dkl: "o", vocN: "collum", vocG: "-i", gen: "n", deu: "der Hals" },
    { typ: "N", dkl: "o", vocN: "colon", vocG: "-i", gen: "n", deu: "der Grimmdarm" },
    { typ: "N", dkl: "o", vocN: "condylus", vocG: "-i", gen: "m", deu: "der Gelenkknochen" },
    { typ: "N", dkl: "o", vocN: "cranium", vocG: "-i", gen: "n", deu: "der Schädel" },
    { typ: "N", dkl: "o", vocN: "digitus", vocG: "-i", gen: "m", deu: "der Finger, die Zehe" },
    { typ: "N", dkl: "o", vocN: "discus", vocG: "-i", gen: "m", deu: "die Scheibe" },
    { typ: "N", dkl: "o", vocN: "dorsum", vocG: "-i", gen: "n", deu: "der Rücken" },
    { typ: "N", dkl: "o", vocN: "duodenum", vocG: "-i", gen: "n", deu: "der Zwölffingerdarm" },
    { typ: "N", dkl: "o", vocN: "epicondylus", vocG: "-i", gen: "m", deu: "der Fortsatz auf dem Gelenkknochen" },
    { typ: "N", dkl: "o", vocN: "fasciculus", vocG: "-i", gen: "m", deu: "das kleine Bündel, der Faserstrang" },
    { typ: "N", dkl: "o", vocN: "fonticulus", vocG: "-i", gen: "m", deu: "die kleine Quelle, die Fontanelle" },
    { typ: "N", dkl: "o", vocN: "frenulum", vocG: "-i", gen: "n", deu: "das Bändchen" },
    { typ: "N", dkl: "o", vocN: "fundus", vocG: "-i", gen: "m", deu: "der Boden, der Grund" },
    { typ: "N", dkl: "o", vocN: "fungus", vocG: "-i", gen: "m", deu: "der Pilz" },
    { typ: "N", dkl: "o", vocN: "ganglion", vocG: "-i", gen: "n", deu: "der Nervenknoten; das Überbein" },
    { typ: "N", dkl: "o", vocN: "globus", vocG: "-i", gen: "m", deu: "die Kugel" },
    { typ: "N", dkl: "o", vocN: "granulum", vocG: "-i", gen: "n", deu: "das Körnchen" },
    { typ: "N", dkl: "o", vocN: "gyrus", vocG: "-i", gen: "m", deu: "die Windung" },
    { typ: "N", dkl: "o", vocN: "hamulus", vocG: "-i", gen: "m", deu: "der kleine Haken" },
    { typ: "N", dkl: "o", vocN: "haustrum", vocG: "-i", gen: "n", deu: "das Schöpfrad, die Ausbuchtung des Dickdarms" },
    { typ: "N", dkl: "o", vocN: "humerus", vocG: "-i", gen: "m", deu: "der Oberarmknochen" },
    { typ: "N", dkl: "o", vocN: "ileum", vocG: "-i", gen: "n", deu: "der Krummdarm" },
    { typ: "N", dkl: "o", vocN: "ileus", vocG: "-i", gen: "m", deu: "der Darmverschluss" },
    { typ: "N", dkl: "o", vocN: "integumentum", vocG: "-i", gen: "n", deu: "die Haut" },
    { typ: "N", dkl: "o", vocN: "intestinum", vocG: "-i", gen: "n", deu: "der Darm" },
    { typ: "N", dkl: "o", vocN: "ischium", vocG: "-i", gen: "n", deu: "die Hüfte, das Gesäß" },
    { typ: "N", dkl: "o", vocN: "jejunum", vocG: "-i", gen: "n", deu: "der Leerdarm" },
    { typ: "N", dkl: "o", vocN: "jugum", vocG: "-i", gen: "n", deu: "das Joch" },
    { typ: "N", dkl: "o", vocN: "labium", vocG: "-i", gen: "n", deu: "die Lippe (paarig)" },
    { typ: "N", dkl: "o", vocN: "labrum", vocG: "-i", gen: "n", deu: "die Lippe (unpaarig)" },
    { typ: "N", dkl: "o", vocN: "ligamentum", vocG: "-i", gen: "n", deu: "das Band" },
    { typ: "N", dkl: "o", vocN: "limbus", vocG: "-i", gen: "m", deu: "der Saum, der Gürtel, der Streifen" },
    { typ: "N", dkl: "o", vocN: "lobus", vocG: "-i", gen: "m", deu: "der Lappen" },
    { typ: "N", dkl: "o", vocN: "lumbus", vocG: "-i", gen: "m", deu: "die Lende" },
    { typ: "N", dkl: "o", vocN: "malleus", vocG: "-i", gen: "m", deu: "der Hammer" },
    { typ: "N", dkl: "o", vocN: "mediastinum", vocG: "-i", gen: "n", deu: "das Mittelfell" },
    { typ: "N", dkl: "o", vocN: "mentum", vocG: "-i", gen: "n", deu: "das Kinn" },
    { typ: "N", dkl: "o", vocN: "mesenterium", vocG: "-i", gen: "n", deu: "das Gekröse" },
    { typ: "N", dkl: "o", vocN: "mesocolon ", vocG: "-i", gen: "n", deu: "Dickdarmgekröse" },
    { typ: "N", dkl: "o", vocN: "metacarpus", vocG: "-i", gen: "m", deu: "die Mittelhand" },
    { typ: "N", dkl: "o", vocN: "metatarsus", vocG: "-i", gen: "m", deu: "der Mittelfuß" },
    { typ: "N", dkl: "o", vocN: "morbus", vocG: "-i", gen: "m", deu: "die Krankheit" },
    { typ: "N", dkl: "o", vocN: "mucus", vocG: "-i", gen: "m", deu: "der Schleim" },
    { typ: "N", dkl: "o", vocN: "musculus", vocG: "-i", gen: "m", deu: "das Mäuschen, der Muskel" },
    { typ: "N", dkl: "o", vocN: "naevus", vocG: "-i", gen: "m", deu: "der Fleck" },
    { typ: "N", dkl: "o", vocN: "nasus", vocG: "-i", gen: "m", deu: "die Nase" },
    { typ: "N", dkl: "o", vocN: "nervus", vocG: "-i", gen: "m", deu: "der Nerv" },
    { typ: "N", dkl: "o", vocN: "nodus", vocG: "-i", gen: "m", deu: "der Knoten" },
    { typ: "N", dkl: "o", vocN: "nucleus", vocG: "-i", gen: "m", deu: "der Kern" },
    { typ: "N", dkl: "o", vocN: "occipitium", vocG: "-i", gen: "n", deu: "der Hinterkopf" },
    { typ: "N", dkl: "o", vocN: "oculus", vocG: "-i", gen: "m", deu: "das Auge" },
    { typ: "N", dkl: "o", vocN: "oesophagus", vocG: "-i", gen: "m", deu: "die Speiseröhre" },
    { typ: "N", dkl: "o", vocN: "olecranon", vocG: "-i", gen: "n", deu: "der Ellbogenhöcker" },
    { typ: "N", dkl: "o", vocN: "omentum", vocG: "-i", gen: "n", deu: "das Netz" },
    { typ: "N", dkl: "o", vocN: "ostium", vocG: "-i", gen: "n", deu: "die Mündung" },
    { typ: "N", dkl: "o", vocN: "ovarium", vocG: "-i", gen: "n", deu: "der Eierstock" },
    { typ: "N", dkl: "o", vocN: "palatum", vocG: "-i", gen: "n", deu: "der Gaumen" },
    { typ: "N", dkl: "o", vocN: "pallium", vocG: "-i", gen: "n", deu: "der Mantel, die Decke, das Tuch; der Hirnmantel" },
    { typ: "N", dkl: "o", vocN: "parodontium", vocG: "-i", gen: "n", deu: "das Zahnbett, der Zahnhalteaparat" },
    { typ: "N", dkl: "o", vocN: "pedunculus", vocG: "-i", gen: "m", deu: "das Füßchen" },
    { typ: "N", dkl: "o", vocN: "peritoneum", vocG: "-i", gen: "n", deu: "das Bauchfell" },
    { typ: "N", dkl: "o", vocN: "philtrum", vocG: "-i", gen: "n", deu: "die Rinne vom Nasenseptum zur Oberlippe" },
    { typ: "N", dkl: "o", vocN: "pilus", vocG: "-i", gen: "m", deu: "das Haar" },
    { typ: "N", dkl: "o", vocN: "polus", vocG: "-i", gen: "m", deu: "die Achse, der Drehpunkt, der Pol" },
    { typ: "N", dkl: "o", vocN: "porus", vocG: "-i", gen: "m", deu: "der Durchgang, die Röhre, das Loch" },
    { typ: "N", dkl: "o", vocN: "prolabium", vocG: "-i", gen: "n", deu: "der Lippenwulst, das Lippenrot" },
    { typ: "N", dkl: "o", vocN: "radius", vocG: "-i", gen: "m", deu: "der Strahl, die Speiche" },
    { typ: "N", dkl: "o", vocN: "ramus", vocG: "-i", gen: "m", deu: "der Ast" },
    { typ: "N", dkl: "o", vocN: "rectum", vocG: "-i", gen: "n", deu: "der Mastdarm" },
    { typ: "N", dkl: "o", vocN: "retinaculum", vocG: "-i", gen: "n", deu: "das Halteband" },
    { typ: "N", dkl: "o", vocN: "septum", vocG: "-i", gen: "n", deu: "die Scheidewand" },
    { typ: "N", dkl: "o", vocN: "sonus", vocG: "-i", gen: "m", deu: "der Ton" },
    { typ: "N", dkl: "o", vocN: "sternum", vocG: "-i", gen: "n", deu: "das Brustbein" },
    { typ: "N", dkl: "o", vocN: "stratum", vocG: "-i", gen: "n", deu: "die Schicht, die Decke" },
    { typ: "N", dkl: "o", vocN: "sulcus", vocG: "-i", gen: "m", deu: "die Furche, die Rinne" },
    { typ: "N", dkl: "o", vocN: "talus", vocG: "-i", gen: "m", deu: "das Sprungbein" },
    { typ: "N", dkl: "o", vocN: "tarsus", vocG: "-i", gen: "m", deu: "die Fußwurzel" },
    { typ: "N", dkl: "o", vocN: "thrombus", vocG: "-i", gen: "m", deu: "das Blutgerinnsel" },
    { typ: "N", dkl: "o", vocN: "trigonum", vocG: "-i", gen: "n", deu: "das Dreieck" },
    { typ: "N", dkl: "o", vocN: "truncus", vocG: "-i", gen: "m", deu: "der Stamm" },
    { typ: "N", dkl: "o", vocN: "tuberculum", vocG: "-i", gen: "n", deu: "der kleine Höcker" },
    { typ: "N", dkl: "o", vocN: "tympanum", vocG: "-i", gen: "n", deu: "die Trommel, Pauke" },
    { typ: "N", dkl: "o", vocN: "uterus", vocG: "-i", gen: "m", deu: "die Gebärmutter" },
    { typ: "N", dkl: "o", vocN: "velum", vocG: "-i", gen: "n", deu: "das Segel" },
    { typ: "N", dkl: "o", vocN: "ventriculus", vocG: "-i", gen: "m", deu: "die Herzkammer" },
    { typ: "N", dkl: "o", vocN: "vestibulum", vocG: "-i", gen: "n", deu: "der Vorhof" },
    { typ: "N", dkl: "o", vocN: "virus", vocG: "-i", gen: "n", deu: "das Virus" },

    { typ: "N", dkl: "k", vocN: "abdomen", vocG: "abdominis", gen: "n", deu: "der Unterleib, der Bauch" },
    { typ: "N", dkl: "k", vocN: "abductor", vocG: "abductoris", gen: "m", deu: "der Abzieher, der Abspreizer, der Wegführer" },
    { typ: "N", dkl: "k", vocN: "ablatio", vocG: "ablationis", gen: "f", deu: "die Wegnahme, die Abtragung" },
    { typ: "N", dkl: "k", vocN: "abrasio", vocG: "abrasionis", gen: "f", deu: "das Abschaben" },
    { typ: "N", dkl: "k", vocN: "acceleratio", vocG: "accelerationis", gen: "f", deu: "die Beschleunigung" },
    { typ: "N", dkl: "k", vocN: "adductor", vocG: "adductoris", gen: "m", deu: "der Heranführer" },
    { typ: "N", dkl: "k", vocN: "adipositas", vocG: "adipositatis", gen: "f", deu: "die Fettleibigkeit" },
    { typ: "N", dkl: "k", vocN: "adhaesio", vocG: "adhaesionis", gen: "f", deu: "das Anhängen, das Anhaften" },
    { typ: "N", dkl: "k", vocN: "aggregatio", vocG: "aggregationis", gen: "f", deu: "das Zusammenhäufen, das Anhäufen" },
    { typ: "N", dkl: "k", vocN: "apex", vocG: "apicis", gen: "m", deu: "die Spitze, die Kuppe" },
    { typ: "N", dkl: "k", vocN: "appendicitis", vocG: "appendicitidis", gen: "f", deu: "die Entzündung des Wurmfortsatzes" },
    {
        typ: "N",
        dkl: "k",
        vocN: "articulatio",
        vocG: "articulationis",
        gen: "f",
        deu: "das Gelenk; (zahnmedizinisch: die Unterkieferbewegung unter Zahnkontakt; logopädisch: die Sprechlautbildung)"
    },
    { typ: "N", dkl: "k", vocN: "auscultatio", vocG: "auscultationis", gen: "f", deu: "das Abhorchen" },
    { typ: "N", dkl: "k", vocN: "calor", vocG: "caloris", gen: "m", deu: "die Wärme" },
    { typ: "N", dkl: "k", vocN: "caput", vocG: "capitis", gen: "n", deu: "der Kopf" },
    { typ: "N", dkl: "k", vocN: "cartilago", vocG: "cartilaginis", gen: "f", deu: "der Knorpel" },
    { typ: "N", dkl: "k", vocN: "cavitas", vocG: "cavitatis", gen: "f", deu: "die Höhlung, der Hohlraum" },
    { typ: "N", dkl: "k", vocN: "cervix", vocG: "cervicis", gen: "f", deu: "der Hals" },
    { typ: "N", dkl: "k", vocN: "chiasma", vocG: "chiasmatis", gen: "n", deu: "die Kreuzung" },
    { typ: "N", dkl: "k", vocN: "color", vocG: "coloris", gen: "m", deu: "die Farbe" },
    { typ: "N", dkl: "k", vocN: "coma", vocG: "comatis", gen: "n", deu: "die Bewusstlosigkeit" },
    { typ: "N", dkl: "k", vocN: "compressio", vocG: "compressionis", gen: "f", deu: "das Zusammendrücken" },
    { typ: "N", dkl: "k", vocN: "contusio", vocG: "contusionis", gen: "f", deu: "das Zudrücken, das Quetschen" },
    { typ: "N", dkl: "k", vocN: "corpus", vocG: "corporis", gen: "n", deu: "der Körper" },
    { typ: "N", dkl: "k", vocN: "cortex", vocG: "corticis", gen: "m", deu: "die Rinde" },
    { typ: "N", dkl: "k", vocN: "crus", vocG: "cruris", gen: "n", deu: "der Schenkel, der Unterschenkel" },
    { typ: "N", dkl: "k", vocN: "crux", vocG: "crucis", gen: "f", deu: "das Kreuz" },
    { typ: "N", dkl: "k", vocN: "dentitio", vocG: "dentitionis", gen: "f", deu: "die Zahnung" },
    { typ: "N", dkl: "k", vocN: "diaphragma", vocG: "diaphragmatis", gen: "n", deu: "das Zwerchfell" },
    { typ: "N", dkl: "k", vocN: "dolor", vocG: "doloris", gen: "m", deu: "der Schmerz" },
    { typ: "N", dkl: "k", vocN: "epididymis", vocG: "epididymidis", gen: "f", deu: "der Nebenhoden" },
    { typ: "N", dkl: "k", vocN: "epiglottis", vocG: "epiglottidis", gen: "f", deu: "der Kehldeckel" },
    { typ: "N", dkl: "k", vocN: "excisio", vocG: "excisionis", gen: "f", deu: "das Ausschneiden" },
    { typ: "N", dkl: "k", vocN: "extensor", vocG: "extensoris", gen: "m", deu: "der Strecker" },
    { typ: "N", dkl: "k", vocN: "femur", vocG: "femoris", gen: "n", deu: "der Oberschenkel" },
    { typ: "N", dkl: "k", vocN: "flexor", vocG: "flexoris", gen: "m", deu: "der Beuger" },
    { typ: "N", dkl: "k", vocN: "foramen", vocG: "foraminis", gen: "n", deu: "das Loch" },
    { typ: "N", dkl: "k", vocN: "formatio", vocG: "formationis", gen: "f", deu: "die Ausbildung, die Gestaltung" },
    { typ: "N", dkl: "k", vocN: "fornix", vocG: "fornicis", gen: "m", deu: "der Bogen, die Wölbung" },
    { typ: "N", dkl: "k", vocN: "functio", vocG: "functionis", gen: "f", deu: "die Aufgabe, die Funktion" },
    { typ: "N", dkl: "k", vocN: "glottis", vocG: "glottidis", gen: "f", deu: "die Stimmritze" },
    { typ: "N", dkl: "k", vocN: "graviditas", vocG: "graviditatis", gen: "f", deu: "die Schwangerschaft" },
    { typ: "N", dkl: "k", vocN: "hallux", vocG: "hallucis", gen: "m", deu: "die Großzehe" },
    { typ: "N", dkl: "k", vocN: "hepar", vocG: "hepatis*", gen: "n", deu: "die Leber" },
    { typ: "N", dkl: "k", vocN: "homo", vocG: "hominis", gen: "m", deu: "der Mensch, der Mann" },
    { typ: "N", dkl: "k", vocN: "incus", vocG: "incudis", gen: "f", deu: "der Amboss" },
    { typ: "N", dkl: "k", vocN: "iris", vocG: "iridis", gen: "f", deu: "die Regenbogenhaut" },
    { typ: "N", dkl: "k", vocN: "larynx", vocG: "laryngis", gen: "m", deu: "der Kehlkopf" },
    { typ: "N", dkl: "k", vocN: "levator", vocG: "levatoris", gen: "m", deu: "der Heber" },
    { typ: "N", dkl: "k", vocN: "lien", vocG: "lienis", gen: "m", deu: "die Milz" },
    { typ: "N", dkl: "k", vocN: "liquor", vocG: "liquoris", gen: "m", deu: "die Flüssigkeit" },
    { typ: "N", dkl: "k", vocN: "lues", vocG: "luis", gen: "f", deu: "die Seuche, (die Syphilis)" },
    { typ: "N", dkl: "k", vocN: "margo", vocG: "marginis", gen: "m", deu: "der Rand" },
    { typ: "N", dkl: "k", vocN: "masseter", vocG: "masseteris", gen: "m", deu: "der Kaumuskel" },
    { typ: "N", dkl: "k", vocN: "mater", vocG: "matris", gen: "f", deu: "die Mutter; anat. die Umhüllung" },
    { typ: "N", dkl: "k", vocN: "meninx", vocG: "meningis", gen: "f", deu: "die Hirnhaut, die Rückenmarkshaut" },
    { typ: "N", dkl: "k", vocN: "motio", vocG: "motionis", gen: "f", deu: "die Bewegung" },
    { typ: "N", dkl: "k", vocN: "mus", vocG: "muris", gen: "m", deu: "die Maus" },
    { typ: "N", dkl: "k", vocN: "os", vocG: "oris", gen: "n", deu: "der Mund" },
    { typ: "N", dkl: "k", vocN: "pancreas", vocG: "pancreatis", gen: "n", deu: "die Bauchspeicheldrüse" },
    { typ: "N", dkl: "k", vocN: "paries", vocG: "parietis", gen: "m", deu: "die Wand, die Seite" },
    { typ: "N", dkl: "k", vocN: "parotis", vocG: "parotidis", gen: "f", deu: "die Ohrspeicheldrüse" },
    { typ: "N", dkl: "k", vocN: "pecten", vocG: "pectinis", gen: "m", deu: "der Kamm" },
    { typ: "N", dkl: "k", vocN: "pectus", vocG: "pectoris", gen: "n", deu: "die Brust, der Brustkorb" },
    { typ: "N", dkl: "k", vocN: "pes", vocG: "pedis", gen: "m", deu: "der Fuß" },
    { typ: "N", dkl: "k", vocN: "pharynx", vocG: "pharyngis*", gen: "m", deu: "der Schlund, der Rachen" },
    { typ: "N", dkl: "k", vocN: "pollex", vocG: "pollicis", gen: "m", deu: "der Daumen" },
    { typ: "N", dkl: "k", vocN: "pubertas", vocG: "pubertatis", gen: "f", deu: "die Pubertät" },
    { typ: "N", dkl: "k", vocN: "pulmo", vocG: "pulmonis", gen: "m", deu: "die Lunge" },
    { typ: "N", dkl: "k", vocN: "pus", vocG: "puris", gen: "n", deu: "der Eiter" },
    { typ: "N", dkl: "k", vocN: "radix", vocG: "radicis", gen: "f", deu: "die Wurzel" },
    { typ: "N", dkl: "k", vocN: "regio", vocG: "regionis", gen: "f", deu: "die Region, das Gebiet" },
    { typ: "N", dkl: "k", vocN: "ren", vocG: "renis", gen: "m", deu: "die Niere" },
    { typ: "N", dkl: "k", vocN: "rotator", vocG: "rotatoris", gen: "m", deu: "der Dreher" },
    { typ: "N", dkl: "k", vocN: "rubor", vocG: "ruboris", gen: "m", deu: "die Rötung" },
    { typ: "N", dkl: "k", vocN: "salpinx", vocG: "salpingis*", gen: "f", deu: "die Trompete; der Eileiter" },
    { typ: "N", dkl: "k", vocN: "sanguis", vocG: "sanguinis", gen: "m", deu: "das Blut" },
    { typ: "N", dkl: "k", vocN: "sectio", vocG: "sectionis", gen: "f", deu: "der Schnitt" },
    { typ: "N", dkl: "k", vocN: "sphincter", vocG: "sphincteris", gen: "m", deu: "der Schließmuskel" },
    { typ: "N", dkl: "k", vocN: "stapes", vocG: "stapedis", gen: "m", deu: "der Steigbügel" },
    { typ: "N", dkl: "k", vocN: "stoma", vocG: "stomatis", gen: "n", deu: "der Mund" },
    { typ: "N", dkl: "k", vocN: "sudor", vocG: "sudoris", gen: "m", deu: "der Schweiß" },
    { typ: "N", dkl: "k", vocN: "tempus", vocG: "temporis", gen: "n", deu: "die Zeit, die Schläfe" },
    { typ: "N", dkl: "k", vocN: "tendo", vocG: "tendinis", gen: "m", deu: "die Sehne" },
    { typ: "N", dkl: "k", vocN: "thorax", vocG: "thoracis", gen: "m", deu: "der Brustkorb" },
    { typ: "N", dkl: "k", vocN: "trauma", vocG: "traumatis", gen: "n", deu: "die Verletzung" },
    { typ: "N", dkl: "k", vocN: "tremor", vocG: "tremoris", gen: "m", deu: "das Zittern" },
    { typ: "N", dkl: "k", vocN: "trochanter", vocG: "trochanteris", gen: "m", deu: "der Rollhügel" },
    { typ: "N", dkl: "k", vocN: "tuber", vocG: "tuberis", gen: "n", deu: "der Höcker" },
    { typ: "N", dkl: "k", vocN: "tuberositas", vocG: "tuberositatis", gen: "f", deu: "die Rauhigkeit" },
    { typ: "N", dkl: "k", vocN: "tumor", vocG: "tumoris", gen: "m", deu: "die Schwellung" },
    { typ: "N", dkl: "k", vocN: "ulcus", vocG: "ulceris", gen: "n", deu: "das Geschwür" },
    { typ: "N", dkl: "k", vocN: "ureter", vocG: "ureteris", gen: "m", deu: "der Harnleiter" },
    { typ: "N", dkl: "k", vocN: "vomer", vocG: "vomeris", gen: "m", deu: "das Pflugscharbein" },

    { typ: "N", dkl: "i", vocN: "animal", vocG: "animalis", gen: "n", deu: "das Tier" },
    { typ: "N", dkl: "i", vocN: "auris", vocG: "auris", gen: "f", deu: "das Ohr" },
    { typ: "N", dkl: "i", vocN: "axis", vocG: "axis", gen: "m", deu: "die Achse, der Pol" },
    { typ: "N", dkl: "i", vocN: "basis", vocG: "basis", gen: "f", deu: "die Grundfläche" },
    { typ: "N", dkl: "i", vocN: "bilis", vocG: "bilis", gen: "f", deu: "die Galle" },
    { typ: "N", dkl: "i", vocN: "calcar", vocG: "-calcaris", gen: "n", deu: "der Sporn" },
    { typ: "N", dkl: "i", vocN: "canalis", vocG: "canalis", gen: "m", deu: "die Rinne, der Kanal" },
    { typ: "N", dkl: "i", vocN: "clavis", vocG: "clavis", gen: "f", deu: "der Schlüssel" },
    { typ: "N", dkl: "i", vocN: "collis", vocG: "collis", gen: "m", deu: "der Hügel" },
    { typ: "N", dkl: "i", vocN: "cutis", vocG: "cutis", gen: "f", deu: "die Haut, die Hülle" },
    { typ: "N", dkl: "i", vocN: "dens", vocG: "dentis", gen: "m", deu: "der Zahn" },
    { typ: "N", dkl: "i", vocN: "falx", vocG: "falcis", gen: "f", deu: "die Sichel" },
    { typ: "N", dkl: "i", vocN: "febris", vocG: "febris", gen: "f", deu: "das Fieber" },
    { typ: "N", dkl: "i", vocN: "fons", vocG: "fontis", gen: "m", deu: "die Quelle" },
    { typ: "N", dkl: "i", vocN: "frons", vocG: "frontis", gen: "f", deu: "die Stirn" },
    { typ: "N", dkl: "i", vocN: "gaster", vocG: "gastris", gen: "f", deu: "der Magen" },
    { typ: "N", dkl: "i", vocN: "glans", vocG: "glandis", gen: "f", deu: "die Eichel" },
    { typ: "N", dkl: "i", vocN: "ile", vocG: "ilis", gen: "n", deu: "der Unterleib" },
    { typ: "N", dkl: "i", vocN: "lens", vocG: "lentis", gen: "f", deu: "die Linse" },
    { typ: "N", dkl: "i", vocN: "mens", vocG: "mentis", gen: "f", deu: "der Verstand" },
    { typ: "N", dkl: "i", vocN: "mensis", vocG: "mensis", gen: "m", deu: "der Monat (Pl. monatliche Blutungen)" },
    { typ: "N", dkl: "i", vocN: "mons", vocG: "montis", gen: "m", deu: "der Berg" },
    { typ: "N", dkl: "i", vocN: "mors", vocG: "mortis", gen: "f", deu: "der Tod" },
    { typ: "N", dkl: "i", vocN: "nox", vocG: "noctis", gen: "f", deu: "die Nacht" },
    { typ: "N", dkl: "i", vocN: "pars", vocG: "partis", gen: "f", deu: "der Teil" },
    { typ: "N", dkl: "i", vocN: "pons", vocG: "pontis", gen: "m", deu: "die Brücke" },
    { typ: "N", dkl: "i", vocN: "pubes", vocG: "pubis", gen: "f", deu: "die Scham" },
    { typ: "N", dkl: "i", vocN: "rete", vocG: "retis", gen: "n", deu: "das Netz" },
    { typ: "N", dkl: "i", vocN: "pelvis", vocG: "pelvis", gen: "f", deu: "das Becken" },
    { typ: "N", dkl: "i", vocN: "testis", vocG: "testis", gen: "m", deu: "der Hoden" },
    { typ: "N", dkl: "i", vocN: "tussis", vocG: "tussis", gen: "f", deu: "der Husten" },
    { typ: "N", dkl: "i", vocN: "unguis", vocG: "unguis", gen: "m", deu: "der Nagel" },
    { typ: "N", dkl: "i", vocN: "venter", vocG: "ventris", gen: "m", deu: "der Bauch, der Leib" },
    { typ: "N", dkl: "i", vocN: "vermis", vocG: "vermis", gen: "m", deu: "der Wurm" },

    { typ: "N", dkl: "iS", vocN: "", vocG: "", vocNP: "natales", vocGP: "natalium", gen: "m", deu: "die Geburt" },
    { typ: "N", dkl: "iS", vocN: "", vocG: "", vocNP: "fauces", vocGP: "faucium", gen: "f", deu: "der Schlund, die Kehle" },
    { typ: "N", dkl: "iS", vocN: "", vocG: "", vocNP: "faeces", vocGP: "faecium", gen: "f", deu: "die Fäkalien, der Kot, der Stuhl" },
    { typ: "N", dkl: "iS", vocN: "cor", vocG: "cordis", vocNP: "corda", vocGP: "cordium", gen: "n", deu: "die Leber" },
    { typ: "N", dkl: "iS", vocN: "hepar", vocG: "hepatis", vocNP: "hepata", vocGP: "hepatum", gen: "n", deu: "die Leber" },
    { typ: "N", dkl: "iS", vocN: "lac", vocG: "lactis", vocNP: "lacta", vocGP: "lactium", gen: "n", deu: "die Milch" },
    { typ: "N", dkl: "iS", vocN: "os", vocG: "ossis", vocNP: "ossa", vocGP: "ossium", gen: "n", deu: "der Knochen" },
    { typ: "N", dkl: "iS", vocN: "vas", vocG: "vasis", vocNP: "vasa", vocGP: "vasorum", gen: "n", deu: "das Gefäß" },

    { typ: "N", dkl: "u", vocN: "cornu", vocG: "-us", gen: "n", deu: " das Horn" },
    { typ: "N", dkl: "u", vocN: "genu", vocG: "-us", gen: "n", deu: "das Knie" },
    { typ: "N", dkl: "u", vocN: "abortus", vocG: "-us", gen: "m", deu: "die Fehlgeburt" },
    { typ: "N", dkl: "u", vocN: "abscessus", vocG: "-us", gen: "m", deu: "die Absiedlung > das Eitergeschwür" },
    { typ: "N", dkl: "u", vocN: "abusus", vocG: "-us", gen: "m", deu: "der Missbrauch" },
    { typ: "N", dkl: "u", vocN: "aditus", vocG: "-us", gen: "m", deu: "der Zugang, der Zutritt, der Eingang" },
    { typ: "N", dkl: "u", vocN: "aquaeductus", vocG: "-us", gen: "m", deu: "die Wasserleitung" },
    { typ: "N", dkl: "u", vocN: "arcus", vocG: "-us", gen: "m", deu: "der Bogen" },
    { typ: "N", dkl: "u", vocN: "auditus", vocG: "-us", gen: "m", deu: "das Hören, das Gehör" },
    { typ: "N", dkl: "u", vocN: "casus", vocG: "-us", gen: "m", deu: "der Fall, der Krankheitsfall" },
    { typ: "N", dkl: "u", vocN: "ductus", vocG: "-us", gen: "m", deu: "der Gang" },
    { typ: "N", dkl: "u", vocN: "exitus", vocG: "-us", gen: "m", deu: "der Ausgang, der Tod" },
    { typ: "N", dkl: "u", vocN: "flatus", vocG: "-us", gen: "m", deu: "die Blähung" },
    { typ: "N", dkl: "u", vocN: "foetus", vocG: "-us", gen: "m", deu: "die Leibesfrucht" },
    { typ: "N", dkl: "u", vocN: "gustus", vocG: "-us", gen: "m", deu: "der Geschmackssinn" },
    { typ: "N", dkl: "u", vocN: "habitus", vocG: "-us", gen: "m", deu: "die Haltung, die (äußere) Körperbeschaffenheit" },
    { typ: "N", dkl: "u", vocN: "hiatus", vocG: "-us", gen: "m", deu: "die Öffnung, der Spalt" },
    { typ: "N", dkl: "u", vocN: "manus", vocG: "-us", gen: "f", deu: "die Hand" },
    { typ: "N", dkl: "u", vocN: "meatus", vocG: "-us", gen: "m", deu: "der Gang" },
    { typ: "N", dkl: "u", vocN: "partus", vocG: "-us", gen: "m", deu: "die Entbindung" },
    { typ: "N", dkl: "u", vocN: "plexus", vocG: "-us", gen: "m", deu: "das Geflecht (von Nerven und Gefäßen)" },
    { typ: "N", dkl: "u", vocN: "processus", vocG: "-us", gen: "m", deu: "der Vorsprung, der Fortsatz" },
    { typ: "N", dkl: "u", vocN: "recessus", vocG: "-us", gen: "m", deu: "die Vertiefung, die Ein-/Ausbuchtung" },
    { typ: "N", dkl: "u", vocN: "sensus", vocG: "-us", gen: "m", deu: "der Sinn, das Gefühl" },
    { typ: "N", dkl: "u", vocN: "sinus", vocG: "-us", gen: "m", deu: "die Ausbuchtung, der Hohlraum, der Blutleiter" },
    { typ: "N", dkl: "u", vocN: "situs", vocG: "-us", gen: "m", deu: "der Ort, die Lage" },
    { typ: "N", dkl: "u", vocN: "tractus", vocG: "-us", gen: "m", deu: "der Zug, der Strang (von Muskel- oder Nervenfasern)" },

    { typ: "N", dkl: "e", vocN: "caries", vocG: "cariei", gen: "f", deu: "der Knochenfraß, die Zahnfäule" },
    { typ: "N", dkl: "e", vocN: "facies", vocG: "faciei", gen: "f", deu: "das Gesicht, die Außenfläche" },
    { typ: "N", dkl: "e", vocN: "rabies", vocG: "crabiei", gen: "f", deu: "die Tollwut" },
    { typ: "N", dkl: "e", vocN: "scabies", vocG: "scabiei", gen: "f", deu: "die Krätze" },
    { typ: "N", dkl: "e", vocN: "species", vocG: "speciei", gen: "f", deu: "die Gattung" },

    { typ: "A", dkl: "ao", vocM: "acutus", vocF: "-a", vocN: "-um", deu: "scharf, heftig, akut" },
    { typ: "A", dkl: "ao", vocM: "adiposus", vocF: "-a", vocN: "-um", deu: "fettreich, adipös" },
    { typ: "A", dkl: "ao", vocM: "albus", vocF: "-a", vocN: "-um", deu: "weiß" },
    { typ: "A", dkl: "ao", vocM: "arachnoideus", vocF: "-a", vocN: "-um", deu: "dem Spinnengewebe ähnlich" },
    { typ: "A", dkl: "ao", vocM: "auditivus", vocF: "-a", vocN: "-um", deu: "zum Hörsinn gehörend, hörfahig" },
    { typ: "A", dkl: "ao", vocM: "benignus", vocF: "-a", vocN: "-um", deu: "gutartig" },
    { typ: "A", dkl: "ao", vocM: "bilifer", vocF: "bilifer-a", vocN: "bil", deu: "ifer-um galleführend" },
    { typ: "A", dkl: "ao", vocM: "caeruleus/coeruleus", vocF: "-a", vocN: "-um", deu: "blau" },
    { typ: "A", dkl: "ao", vocM: "callosus", vocF: "-a", vocN: "-um", deu: "schwielig, dickhäutig" },
    { typ: "A", dkl: "ao", vocM: "cardiacus", vocF: "-a", vocN: "-um", deu: "zum Magenmund gehörend" },
    { typ: "A", dkl: "ao", vocM: "cavus", vocF: "-a", vocN: "-um", deu: "hohl" },
    { typ: "A", dkl: "ao", vocM: "coeliacus", vocF: "-a", vocN: "-um", deu: "den Magen betreffend" },
    { typ: "A", dkl: "ao", vocM: "coeruleus", vocF: "-a", vocN: "-um", deu: "blau" },
    { typ: "A", dkl: "ao", vocM: "colicus", vocF: "-a", vocN: "-um", deu: "zum Grimmdarm gehörend" },
    { typ: "A", dkl: "ao", vocM: "coronarius", vocF: "-a", vocN: "-um", deu: "kranzförmig" },
    { typ: "A", dkl: "ao", vocM: "coronoideus", vocF: "-a", vocN: "-um", deu: "kranzartig" },
    { typ: "A", dkl: "ao", vocM: "corpulentus", vocF: "-a", vocN: "-um", deu: "korpulent, wohlbeleibt" },
    { typ: "A", dkl: "ao", vocM: "crassus", vocF: "-a", vocN: "-um", deu: "dick" },
    { typ: "A", dkl: "ao", vocM: "cuneatus", vocF: "-a", vocN: "-um", deu: "keilförmig" },
    { typ: "A", dkl: "ao", vocM: "cutaneus", vocF: "-a", vocN: "-um", deu: "zur Haut gehörend" },
    { typ: "A", dkl: "ao", vocM: "cysticus", vocF: "-a", vocN: "-um", deu: "zur Blase gehörend" },
    { typ: "A", dkl: "ao", vocM: "dexter", vocF: "dextr-a", vocN: "dex", deu: "tr-um rechts" },
    { typ: "A", dkl: "ao", vocM: "durus", vocF: "-a", vocN: "-um", deu: "hart" },
    { typ: "A", dkl: "ao", vocM: "exsudativus", vocF: "-a", vocN: "-um", deu: "schwitzend, ausschwitzend" },
    { typ: "A", dkl: "ao", vocM: "externus", vocF: "-a", vocN: "-um", deu: "außen gelegen" },
    { typ: "A", dkl: "ao", vocM: "fibrosus", vocF: "-a", vocN: "-um", deu: "reich an Fasern" },
    { typ: "A", dkl: "ao", vocM: "flavus", vocF: "-a", vocN: "-um", deu: "gelb" },
    { typ: "A", dkl: "ao", vocM: "griseus", vocF: "-a", vocN: "-um", deu: "grau" },
    { typ: "A", dkl: "ao", vocM: "internus", vocF: "-a", vocN: "-um", deu: "innen gelegen, innere" },
    { typ: "A", dkl: "ao", vocM: "lacrimosus", vocF: "-a", vocN: "-um", deu: "tränenreich" },
    { typ: "A", dkl: "ao", vocM: "laesus", vocF: "-a", vocN: "-um", deu: "gestört, defekt" },
    { typ: "A", dkl: "ao", vocM: "latissimus", vocF: "-a", vocN: "-um", deu: "der, die, das breiteste" },
    { typ: "A", dkl: "ao", vocM: "latus", vocF: "-a", vocN: "-um", deu: "breit" },
    { typ: "A", dkl: "ao", vocM: "liber", vocF: "liber-a", vocN: "lib", deu: "er-um frei" },
    { typ: "A", dkl: "ao", vocM: "lividus", vocF: "-a", vocN: "-um", deu: "blau" },
    { typ: "A", dkl: "ao", vocM: "luteus", vocF: "-a", vocN: "-um", deu: "gelb" },
    { typ: "A", dkl: "ao", vocM: "magnus", vocF: "-a", vocN: "-um", deu: "groß" },
    { typ: "A", dkl: "ao", vocM: "malignus", vocF: "-a", vocN: "-um", deu: "bösartig" },
    { typ: "A", dkl: "ao", vocM: "mastoideus", vocF: "-a", vocN: "-um", deu: "warzenartig" },
    { typ: "A", dkl: "ao", vocM: "maximus", vocF: "-a", vocN: "-um", deu: "der, die, das größte" },
    { typ: "A", dkl: "ao", vocM: "medianus", vocF: "-a", vocN: "-um", deu: "genau in der Mittellinie liegend" },
    { typ: "A", dkl: "ao", vocM: "medius", vocF: "-a", vocN: "-um", deu: "der, die, das mittlere (von dreien)" },
    { typ: "A", dkl: "ao", vocM: "morbidus", vocF: "-a", vocN: "-um", deu: "krank" },
    { typ: "A", dkl: "ao", vocM: "niger", vocF: "nigr-a", vocN: "nig", deu: "r-um schwarz" },
    { typ: "A", dkl: "ao", vocM: "nocturnus", vocF: "-a", vocN: "-um", deu: "nächtlich" },
    { typ: "A", dkl: "ao", vocM: "obliquus", vocF: "-a", vocN: "-um", deu: "schräg" },
    { typ: "A", dkl: "ao", vocM: "olfactorius", vocF: "-a", vocN: "-um", deu: "dem Riechen dienend" },
    { typ: "A", dkl: "ao", vocM: "palatinus", vocF: "-a", vocN: "-um", deu: "zum Gaumen gehörend" },
    { typ: "A", dkl: "ao", vocM: "pallidus", vocF: "-a", vocN: "-um", deu: "grau" },
    { typ: "A", dkl: "ao", vocM: "parvus", vocF: "-a", vocN: "-um", deu: "klein" },
    { typ: "A", dkl: "ao", vocM: "pius", vocF: "-a", vocN: "-um", deu: "fromm, mild, gütig" },
    { typ: "A", dkl: "ao", vocM: "profundus", vocF: "-a", vocN: "-um", deu: "tief" },
    { typ: "A", dkl: "ao", vocM: "proprius", vocF: "-a", vocN: "-um", deu: "eigen, eigentlich" },
    { typ: "A", dkl: "ao", vocM: "purpureus", vocF: "-a", vocN: "-um", deu: "purpurrot" },
    { typ: "A", dkl: "ao", vocM: "purulentus", vocF: "-a", vocN: "-um", deu: "eitrig" },
    { typ: "A", dkl: "ao", vocM: "quadratus", vocF: "-a", vocN: "-um", deu: "viereckig" },
    { typ: "A", dkl: "ao", vocM: "quartanus", vocF: "-a", vocN: "-um", deu: "vierte" },
    { typ: "A", dkl: "ao", vocM: "rotundus", vocF: "-a", vocN: "-um", deu: "rund" },
    { typ: "A", dkl: "ao", vocM: "ruber", vocF: "rubr-a", vocN: "rub", deu: "r-um rot" },
    { typ: "A", dkl: "ao", vocM: "sacer", vocF: "sacr-a", vocN: "sac", deu: "r-um heilig" },
    { typ: "A", dkl: "ao", vocM: "secundus", vocF: "-a", vocN: "-um", deu: "zweiter" },
    { typ: "A", dkl: "ao", vocM: "sinister", vocF: "sinistr-a", vocN: "sin", deu: "istr-um links" },
    { typ: "A", dkl: "ao", vocM: "supremus", vocF: "-a", vocN: "-um", deu: "oberster" },
    { typ: "A", dkl: "ao", vocM: "transversus", vocF: "-a", vocN: "-um", deu: "querverlaufend" },
    { typ: "A", dkl: "ao", vocM: "tympanicus", vocF: "-a", vocN: "-um", deu: "zur Pauke gehörend" },
    { typ: "A", dkl: "ao", vocM: "uterinus", vocF: "-a", vocN: "-um", deu: "zur Gebärmutter gehörend" },
    { typ: "A", dkl: "ao", vocM: "vagus", vocF: "-a", vocN: "-um", deu: "weit umherschweifend" },
    { typ: "A", dkl: "ao", vocM: "verus", vocF: "-a", vocN: "-um", deu: "echt, wahr" },
    { typ: "A", dkl: "ao", vocM: "violentus", vocF: "-a", vocN: "-um", deu: "gewaltsam, ungestüm" },
    { typ: "A", dkl: "ao", vocM: "voluntarius", vocF: "-a", vocN: "-um", deu: "freiwillig" },

    { typ: "A", dkl: "k", vocM: "anterior", vocN: "anterius", vocG: "anterioris", deu: "weiter vorn gelegen" },
    { typ: "A", dkl: "k", vocM: "inferior", vocN: "inferius", vocG: "inferioris", deu: "weiter unten gelegen" },
    { typ: "A", dkl: "k", vocM: "major", vocN: "majus", vocG: "majoris", deu: "größer" },
    { typ: "A", dkl: "k", vocM: "minor", vocN: "minus", vocG: "minoris", deu: "kleiner" },
    { typ: "A", dkl: "k", vocM: "posterior", vocN: "posterius", vocG: "posterioris", deu: "weiter hinten gelegen" },
    { typ: "A", dkl: "k", vocM: "superior", vocN: "superius", vocG: "superioris", deu: "weiter oben gelegen" },

    { typ: "A", dkl: "k", vocM: "biceps", vocG: "bicipitis", deu: "zweiköpfig" },
    { typ: "A", dkl: "k", vocM: "triceps", vocG: "tricipitis", deu: "dreiköpfig" },
    { typ: "A", dkl: "k", vocM: "quadriceps", vocG: "quadricipitis", deu: "vierköpfig" },

    { typ: "A", dkl: "i", vocM: "caudalis", vocN: "-e", deu: "steißwärts, nach dem unteren Körperende zu" },
    { typ: "A", dkl: "i", vocM: "brevis", vocN: "-e", deu: "kurz" },
    { typ: "A", dkl: "i", vocM: "cerebralis", vocN: "-e", deu: "zum Gehirn gehörend" },
    { typ: "A", dkl: "i", vocM: "communis", vocN: "-e", deu: "gemeinsam, allgemein" },
    { typ: "A", dkl: "i", vocM: "cranialis", vocN: "-e", deu: "kopfwärts gelegen" },
    { typ: "A", dkl: "i", vocM: "cruciformis", vocN: "-e", deu: "kreuzförmig" },
    { typ: "A", dkl: "i", vocM: "distalis", vocN: "-e", deu: "rumpffern gelegen" },
    { typ: "A", dkl: "i", vocM: "dorsalis", vocN: "-e", deu: "zum Rücken, Hand- od. Fußrücken hin gelegen" },
    { typ: "A", dkl: "i", vocM: "ethmoidalis", vocN: "-e", deu: "siebartig" },
    { typ: "A", dkl: "i", vocM: "facialis", vocN: "-e", deu: "zum Gesicht gehörend" },
    { typ: "A", dkl: "i", vocM: "fibularis", vocN: "-e", deu: "zum Wadenbein gehörend" },
    { typ: "A", dkl: "i", vocM: "flexibilis", vocN: "-e", deu: "biegsam" },
    { typ: "A", dkl: "i", vocM: "frontalis", vocN: "-e", deu: "zur Stirn hin gelegen" },
    { typ: "A", dkl: "i", vocM: "gracilis", vocN: "-e", deu: "dünn, schlank, schmal" },
    { typ: "A", dkl: "i", vocM: "lateralis", vocN: "-e", deu: "seitlich gelegen" },
    { typ: "A", dkl: "i", vocM: "longitudinalis", vocN: "-e", deu: "längs verlaufend, länglich" },
    { typ: "A", dkl: "i", vocM: "medialis", vocN: "-e", deu: "zur Mittellinie hin gelegen" },
    { typ: "A", dkl: "i", vocM: "mollis", vocN: "-e", deu: "weich" },
    { typ: "A", dkl: "i", vocM: "occipitalis", vocN: "-e", deu: "zum Hinterkopf hingelegen" },
    { typ: "A", dkl: "i", vocM: "piriformis", vocN: "-e", deu: "birnenförmig" },
    { typ: "A", dkl: "i", vocM: "pisiformis", vocN: "-e", deu: "erbsenförmig" },
    { typ: "A", dkl: "i", vocM: "proximalis", vocN: "-e", deu: "rumpfnah gelegen" },
    { typ: "A", dkl: "i", vocM: "sagittalis", vocN: "-e", deu: "pfeilartig, in der Pfeilrichtung gelegen" },
    { typ: "A", dkl: "i", vocM: "spinalis", vocN: "-e", deu: "zur Wirbelsäule gehörend" },
    { typ: "A", dkl: "i", vocM: "superficialis", vocN: "-e", deu: "oberflächlich" },
    { typ: "A", dkl: "i", vocM: "temporalis", vocN: "-e", deu: "zur Schläfe gehörend" },
    { typ: "A", dkl: "i", vocM: "tibialis", vocN: "-e", deu: "zum Schienbein gehörend" },
    { typ: "A", dkl: "i", vocM: "transversalis", vocN: "-e", deu: "quer verlaufend" },
    { typ: "A", dkl: "i", vocM: "ulnaris", vocN: "-e", deu: "zur Elle gehörend" },
    { typ: "A", dkl: "i", vocM: "ventralis", vocN: "-e", deu: "zum Bauch hin gelegen" },
    { typ: "A", dkl: "i", vocM: "viridis", vocN: "-e", deu: "grün" },
    { typ: "A", dkl: "i", vocM: "visceralis", vocN: "-e", deu: "eingeweidewärts, organwärts" },

    { typ: "A", dkl: "i", vocM: "abducens", vocG: "abducentis", deu: "wegführend" },
    { typ: "A", dkl: "i", vocM: "afferens", vocG: "afferentis", deu: "heranbringend" },
    { typ: "A", dkl: "i", vocM: "ascendens", vocG: "acsendentis", deu: "aufsteigend" },
    { typ: "A", dkl: "i", vocM: "communicans", vocG: "communicantis", deu: "verbindend" },
    { typ: "A", dkl: "i", vocM: "deferens", vocG: "deferentis", deu: "hinabbringend" },
    { typ: "A", dkl: "i", vocM: "deformans", vocG: "deformantis", deu: "verformend" },
    { typ: "A", dkl: "i", vocM: "demens", vocG: "dementis", deu: "unsinnig, verrückt" },
    { typ: "A", dkl: "i", vocM: "descendens", vocG: "descendentis", deu: "absteigend" },
    { typ: "A", dkl: "i", vocM: "efferens", vocG: "efferentis", deu: "hinausbringend" },
    { typ: "A", dkl: "i", vocM: "obliterans", vocG: "obliterantis", deu: "verstopfend" },
    { typ: "A", dkl: "i", vocM: "perforans", vocG: "peforantis", deu: "durchbohrend" },
    { typ: "A", dkl: "i", vocM: "recurrens", vocG: "recurrentis", deu: "zurücklaufend" },

    { typ: "aS", voc: "-alis", deu: "Zugehörigkeit", bsp: "tibialis" },
    { typ: "aS", voc: "-aris", deu: "Zugehörigkeit", bsp: "fibularis" },
    { typ: "aS", voc: "-icus", deu: "Zugehörigkeit", bsp: "pyloricus" },
    { typ: "aS", voc: "-(i)acus", deu: "Zugehörigkeit", bsp: "cardiacus" },
    { typ: "aS", voc: "-eus", deu: "Zugehörigkeit", bsp: "tarseus" },
    { typ: "aS", voc: "-arius", deu: "Zugehörigkeit", bsp: "coronarius" },

    { typ: "aS", voc: "-orius", deu: "Tätigkeit/Fähigkeit", bsp: "adductorius" },
    { typ: "aS", voc: "-ivus", deu: "Tätigkeit/Fähigkeit", bsp: "incisivus" },

    { typ: "aS", voc: "-(o)ideus", deu: "Ähnlichkeit/Aussehen", bsp: "thyreoideus" },
    { typ: "aS", voc: "-formis", deu: "Ähnlichkeit/Aussehen", bsp: "piriformis" },

    { typ: "aS", voc: "-osus", deu: "Fülle (reich an)", bsp: "adiposus" },
    { typ: "aS", voc: "-lentus", deu: "Fülle (reich an)", bsp: "purulentus" },

    { typ: "aS", voc: "-eus", deu: "(Stoffähnliche) Eigenschaft", bsp: "osseus (knöchern)" },
    { typ: "aS", voc: "-orius", deu: "(Stoffähnliche) Eigenschaft", bsp: "longitudinalis (länglich)" },
    {
        typ: "aS",
        voc: "-atus",
        deu: "Ergebnis eines Vorgangs/Ähnlichkeit/versehen mit etwas",
        bsp: "obturatus (verstopft)\nlunatus (halbmondförmig)\nhamatus (mit einem Hammer versehen)"
    },
    { typ: "P", voc: "a-, ab-, abs-", deu: "von,von – her, von - weg" },
    { typ: "P", voc: "a-, an-", deu: "un-,  -los (Verneinung)" },
    { typ: "P", voc: "ad-", deu: "zu, heran, an" },
    { typ: "P", voc: "ambi-", deu: "beidseitig" },
    { typ: "P", voc: "ana-", deu: "hinauf, auf … hin; auseinander" },
    { typ: "P", voc: "ante-", deu: "vor, vorn" },
    { typ: "P", voc: "anti-", deu: "gegen" },
    { typ: "P", voc: "ap(o)-", deu: "von … weg" },
    { typ: "P", voc: "aut(o)-", deu: "selbst" },
    { typ: "P", voc: "bi-", deu: "zweimal" },
    { typ: "P", voc: "bin-", deu: "je zwei" },
    { typ: "P", voc: "circum-", deu: "(um…) herum, ringsherum" },
    { typ: "P", voc: "com-, con-", deu: "mit-, zusammencontra- gegen" },
    { typ: "P", voc: "de-", deu: "von … weg, herab," },
    { typ: "P", voc: "deka-", deu: "zehn" },
    { typ: "P", voc: "di-", deu: "zweimal" },
    { typ: "P", voc: "dia-", deu: "durch, hindurch; auseinander; zwischen" },
    { typ: "P", voc: "dipl(o)-", deu: "doppel" },
    { typ: "P", voc: "dis-", deu: "auseinander-, ver-, zer-, undys- un-, miß- (dieses Präfix drückt eine Abweichung aus)" },
    { typ: "P", voc: "e-, ex(o)-", deu: "aus, heraus" },
    { typ: "P", voc: "ekto-, exo-", deu: "außerhalb" },
    { typ: "P", voc: "endo-, ento-", deu: "innen, innerhalb" },
    { typ: "P", voc: "epi-, ep-, eph-", deu: "auf, darauf" },
    { typ: "P", voc: "eu-", deu: "gut, wohl" },
    { typ: "P", voc: "extra-", deu: "außerhalb" },
    { typ: "P", voc: "hapl(o)-", deu: "einfach" },
    { typ: "P", voc: "hemi-", deu: "halb" },
    { typ: "P", voc: "hept-", deu: "sieben" },
    { typ: "P", voc: "hex(a)-", deu: "sechs" },
    { typ: "P", voc: "holo-", deu: "ganz, völlig" },
    { typ: "P", voc: "hyper-", deu: "über" },
    { typ: "P", voc: "hyp(o)-", deu: "unter, unterhalb, unter der Norm" },
    { typ: "P", voc: "in-", deu: "in, hinein; un-, -los (Verneinung)" },
    { typ: "P", voc: "infra-", deu: "unterhalb" },
    { typ: "P", voc: "inter-", deu: "zwischen" },
    { typ: "P", voc: "intra-", deu: "innen, innerhalb" },
    { typ: "P", voc: "ipsi-", deu: "selbst" },
    { typ: "P", voc: "iuxta-,", deu: "juxta- dicht daneben, nahe bei" },
    { typ: "P", voc: "kata-", deu: "ab, hinab, danach" },
    { typ: "P", voc: "mes(o)-", deu: "mitten, zwischen" },
    { typ: "P", voc: "meta-", deu: "dahinter, nach; danach (zeitlich)" },
    { typ: "P", voc: "mon(o)-", deu: "allein, einzeln" },
    { typ: "P", voc: "multi-", deu: "viel" },
    { typ: "P", voc: "neo-", deu: "neu" },
    { typ: "P", voc: "novem-", deu: "neun" },
    { typ: "P", voc: "nulli-", deu: "kein" },
    { typ: "P", voc: "oct-", deu: "acht" },
    { typ: "P", voc: "olig(o)-", deu: "wenig" },
    { typ: "P", voc: "orth(o)-", deu: "gerade, richtig" },
    { typ: "P", voc: "par(a)-", deu: "neben" },
    { typ: "P", voc: "pent-", deu: "fünf" },
    { typ: "P", voc: "per-", deu: "durch, hindurch" },
    { typ: "P", voc: "peri-", deu: "(um …) herum, ringsherum" },
    { typ: "P", voc: "poly-", deu: "viel" },
    { typ: "P", voc: "post-", deu: "nach, hinter" },
    { typ: "P", voc: "prae-", deu: "vor, vorher" },
    { typ: "P", voc: "primi-", deu: "erst" },
    { typ: "P", voc: "pro-", deu: "für, vor" },
    { typ: "P", voc: "prot-", deu: "erster, vorderster, wichtigster" },
    { typ: "P", voc: "pseud(o)-", deu: "falsch" },
    { typ: "P", voc: "quadri-", deu: "vier" },
    { typ: "P", voc: "quinqui-", deu: "fünf" },
    { typ: "P", voc: "re-", deu: "wieder-, rück-, neu" },
    { typ: "P", voc: "retro-", deu: "rückwärts, nach hinten" },
    { typ: "P", voc: "se-", deu: "sechs" },
    { typ: "P", voc: "secundi-", deu: "zweit" },
    { typ: "P", voc: "semi-", deu: "halb" },
    { typ: "P", voc: "septem-", deu: "sieben" },
    { typ: "P", voc: "supra-", deu: "oberhalb" },
    { typ: "P", voc: "syn-", deu: "mit, zusammen" },
    { typ: "P", voc: "tel-", deu: "fern, endtetra- vier" },
    { typ: "P", voc: "trans-", deu: "duch, hindurch" },
    { typ: "P", voc: "tri-", deu: "drei" },
    { typ: "P", voc: "uni-", deu: "ein(er)" },

    { typ: "G", voc: "aden-", deu: "Drüse" },
    { typ: "G", voc: "ästhesi-", deu: "die Empfindung, der Schmerz" },
    { typ: "G", voc: "-algie", deu: "der Schmerz" },
    { typ: "G", voc: "andr-", deu: "der Mann" },
    { typ: "G", voc: "angi-", deu: "das Gefäß" },
    { typ: "G", voc: "anthrop-", deu: "der Mensch" },
    { typ: "G", voc: "arthr-", deu: "das Gelenk" },
    { typ: "G", voc: "balan-", deu: "die Eichel" },
    { typ: "G", voc: "blephar-", deu: "das Augenlid" },
    { typ: "G", voc: "bathy-", deu: "tief" },
    { typ: "G", voc: "brachy-", deu: "kurz" },
    { typ: "G", voc: "brady-", deu: "langsam" },
    { typ: "G", voc: "cheil-", deu: "die Lippe" },
    { typ: "G", voc: "chir-", deu: "die Hand" },
    { typ: "G", voc: "chol-", deu: "die Galle" },
    { typ: "G", voc: "chondr-", deu: "der Knorpel" },
    { typ: "G", voc: "cholecyst-", deu: "die Gallenblase" },
    { typ: "G", voc: "choledoch-", deu: "der Gallengang" },
    { typ: "G", voc: "chlor-", deu: "blassgrün, blass" },
    { typ: "G", voc: "daktyl-", deu: "der Finger" },
    { typ: "G", voc: "dermat-, pell-", deu: "die Haut" },
    { typ: "G", voc: "-ektasie", deu: "die Erweiterung" },
    { typ: "G", voc: "-ektomie", deu: "das Herausschneiden" },
    { typ: "G", voc: "-emesis", deu: "das Erbrechen" },
    { typ: "G", voc: "enkephal-", deu: "das Hirn" },
    { typ: "G", voc: "enter-", deu: "der Darm" },
    { typ: "G", voc: "epiplo-", deu: "das Netz" },
    { typ: "G", voc: "erythr-", deu: "rot" },
    { typ: "G", voc: "gastr-", deu: "der Magen" },
    { typ: "G", voc: "glauk-", deu: "grünlich-blau" },
    { typ: "G", voc: "gloss-", deu: "die Zunge" },
    { typ: "G", voc: "gnath-", deu: "der Kiefer" },
    { typ: "G", voc: "-gnose", deu: "die Erkenntnis" },
    { typ: "G", voc: "gon-", deu: "das Knie" },
    { typ: "G", voc: "-graphie", deu: "die Aufzeichnung, die Beschreibung" },
    { typ: "G", voc: "gynäk-", deu: "die Frau" },
    { typ: "G", voc: "häm-, hämat-", deu: "das Blut" },
    { typ: "G", voc: "hydat-, hydr-", deu: "das Wasser" },
    { typ: "G", voc: "hyster-", deu: "die Gebärmutter" },
    { typ: "G", voc: "hidr-", deu: "der Schweiß" },
    { typ: "G", voc: "iatr-", deu: "der Arzt" },
    { typ: "G", voc: "kardi-", deu: "das Herz, der Mageneingang" },
    { typ: "G", voc: "kary-", deu: "der Kern" },
    { typ: "G", voc: "kephal-", deu: "der Kopf" },
    { typ: "G", voc: "kin(et)-", deu: "die Bewegung" },
    { typ: "G", voc: "kolp-", deu: "die Scheide" },
    { typ: "G", voc: "kopr-", deu: "der Kot, der Stuhl" },
    { typ: "G", voc: "kor-", deu: "die Pupille" },
    { typ: "G", voc: "kryo-", deu: "eiskalt" },
    { typ: "G", voc: "kyane-, zyan-", deu: "blau" },
    { typ: "G", voc: "kyst-, zyst-", deu: "die Harnblase, Blase" },
    { typ: "G", voc: "kyt-, ", deu: "zyt- die Zelle" },
    { typ: "G", voc: "lapar-", deu: "der Magen,der Bauch" },
    { typ: "G", voc: "leuk-", deu: "weiß" },
    { typ: "G", voc: "lip-", deu: "das Fett" },
    { typ: "G", voc: "lith-", deu: "der Stein" },
    { typ: "G", voc: "-lithiasis", deu: "das Steinleiden" },
    { typ: "G", voc: "-logie", deu: "die Lehre" },
    { typ: "G", voc: "-lyse", deu: "die Auflösung" },
    { typ: "G", voc: "makr(o)-", deu: "groß, lang" },
    { typ: "G", voc: "mega-, megalo-", deu: "groß, stark" },
    { typ: "G", voc: "mast-", deu: "die weibliche Brustdrüse, die Brust, die Brustwarze" },
    { typ: "G", voc: "mela-", deu: "schwarz" },
    { typ: "G", voc: "metr-", deu: "die Gebärmutter" },
    { typ: "G", voc: "-metrie", deu: "die Messung" },
    { typ: "G", voc: "mikr(o)-", deu: "klein, kurz" },
    { typ: "G", voc: "morph-", deu: "die Gestalt" },
    { typ: "G", voc: "myel-", deu: "das Mark" },
    { typ: "G", voc: "my-", deu: "der Muskel" },
    { typ: "G", voc: "myk-", deu: "der Pilz" },
    { typ: "G", voc: "nekr-", deu: "der Leichnam" },
    { typ: "G", voc: "nephr-", deu: "die Niere" },
    { typ: "G", voc: "neur-", deu: "der Nerv" },
    { typ: "G", voc: "nos-", deu: "die Krankheit" },
    { typ: "G", voc: "odont-", deu: "der Zahn" },
    { typ: "G", voc: "oophor-", deu: "der Eierstock" },
    { typ: "G", voc: "ophthalm-", deu: "das Auge" },
    { typ: "G", voc: "orch-", deu: "der Hoden" },
    { typ: "G", voc: "oste-", deu: "der Knochen" },
    { typ: "G", voc: "ot-", deu: "das Ohr" },
    { typ: "G", voc: "päd-", deu: "das Kind" },
    { typ: "G", voc: "pharmak-", deu: "das Heilmittel" },
    { typ: "G", voc: "path-", deu: "das Leiden, die Krankheit" },
    { typ: "G", voc: "peni-", deu: "die Armut, der Mangel" },
    { typ: "G", voc: "phleb-", deu: "die Vene" },
    { typ: "G", voc: "phys-", deu: "das Wachstum, die Natur" },
    { typ: "G", voc: "platy-", deu: "flach" },
    { typ: "G", voc: "plethy-", deu: "voll" },
    { typ: "G", voc: "pleg-", deu: "der Stoß, die Lähmng" },
    { typ: "G", voc: "pneum-", deu: "die Lunge" },
    { typ: "G", voc: "-pnoe", deu: "der Atem, der Hauch" },
    { typ: "G", voc: "pod-", deu: "der Fuß" },
    { typ: "G", voc: "porphyr-", deu: "purpurrot" },
    { typ: "G", voc: "presby-", deu: "alt" },
    { typ: "G", voc: "prokt-", deu: "der After" },
    { typ: "G", voc: "psych-", deu: "die Seele" },
    { typ: "G", voc: "pyrrho-", deu: "feuerrot" },
    { typ: "G", voc: "raph-", deu: "der Saum, die Nahtlinie" },
    { typ: "G", voc: "rhin-", deu: "die Nase" },
    { typ: "G", voc: "-rrhoe", deu: "der Fluß, das Fließen" },
    { typ: "G", voc: "salping-", deu: "der Eileiter" },
    { typ: "G", voc: "sklero-", deu: "hart" },
    { typ: "G", voc: "skolio-", deu: "krumm" },
    { typ: "G", voc: "-skopie", deu: "das Anschauen, die Spiegelung" },
    { typ: "G", voc: "splanchn-", deu: "der Darm" },
    { typ: "G", voc: "spasm-", deu: "der Krampf" },
    { typ: "G", voc: "spondyl-", deu: "die Wirbel" },
    { typ: "G", voc: "somat-", deu: "der Körper" },
    { typ: "G", voc: "steth-", deu: "die Brust" },
    { typ: "G", voc: "stomat-", deu: "der Mund, die Öffnung" },
    { typ: "G", voc: "tachy-", deu: "schnell" },
    { typ: "G", voc: "therm-", deu: "warm" },
    { typ: "G", voc: "thorac-", deu: "die Brust" },
    { typ: "G", voc: "tom-", deu: "der Schnitt" },
    { typ: "G", voc: "trich-", deu: "das Haar" },
    { typ: "G", voc: "ur-", deu: "der Harn, der Urin" },
    { typ: "G", voc: "xanth-", deu: "gelb" },
    { typ: "G", voc: "xer-", deu: "trocken" },
    { typ: "G", voc: "-zele", deu: "der Bruch" },
    { typ: "G", voc: "zygom-", deu: "das Jochbein" },
    { typ: "G", voc: "zyt-, kyt-", deu: "die Zelle" },
    { typ: "G", voc: "zyst-, kyst-", deu: "die Harnblase, die Blase" },

    { typ: "GL", vocL: "adeps", vocG: "lipos", deu: "das Fett" },
    { typ: "GL", vocL: "anima", vocG: "psyche", deu: "die Seele" },
    { typ: "GL", vocL: "anus, rectum", vocG: "proktos", deu: "der After" },
    { typ: "GL", vocL: "aqua", vocG: "hydor, hydat-, hydr-", deu: "das Wasser" },
    { typ: "GL", vocL: "articulatio", vocG: "arthron", deu: "das Gelenk" },
    { typ: "GL", vocL: "auris", vocG: "ous, ot-", deu: "das Ohr" },
    { typ: "GL", vocL: "bilis, fel", vocG: "chole", deu: "die Galle" },
    { typ: "GL", vocL: "caput", vocG: "kephalon", deu: "der Kopf" },
    { typ: "GL", vocL: "capillus", vocG: "trix, trich-", deu: "das Haar" },
    { typ: "GL", vocL: "cartilago", vocG: "chondros", deu: "der Knorpel" },
    { typ: "GL", vocL: "cellula", vocG: "kytos", deu: "die Zelle" },
    { typ: "GL", vocL: "cerebrum", vocG: "enkephalon", deu: "das Gehirn" },
    { typ: "GL", vocL: "cor", vocG: "kardia", deu: "das Herz" },
    { typ: "GL", vocL: "corpus", vocG: "soma", deu: "der Körper" },
    { typ: "GL", vocL: "cutis", vocG: "derma, pella", deu: "die Haut" },
    { typ: "GL", vocL: "dens", vocG: "odous, odont-", deu: "der Zahn" },
    { typ: "GL", vocL: "digitus", vocG: "daktylos", deu: "der Finger" },
    { typ: "GL", vocL: "faeces", vocG: "kopros", deu: "der Kot, der Stuhl" },
    { typ: "GL", vocL: "femina", vocG: "gyne", deu: "die Frau" },
    { typ: "GL", vocL: "fungus", vocG: "mykos", deu: "der Pilz" },
    { typ: "GL", vocL: "genu", vocG: "gony", deu: "das Knie" },
    { typ: "GL", vocL: "glans", vocG: "balanos", deu: "die Eichel" },
    { typ: "GL", vocL: "glandula", vocG: "aden", deu: "die Drüse" },
    { typ: "GL", vocL: "homo", vocG: "anthropos", deu: "der Mensch" },
    { typ: "GL", vocL: "intestinum", vocG: "enteron", deu: "der Darm" },
    { typ: "GL", vocL: "labium", vocG: "cheilos", deu: "die Lippe" },
    { typ: "GL", vocL: "lien", vocG: "splen", deu: "die Milz" },
    { typ: "GL", vocL: "lingua", vocG: "glossa", deu: "die Zunge" },
    { typ: "GL", vocL: "mamma", vocG: "mastos", deu: "die weibl. Brustdrüse, die Brust" },
    { typ: "GL", vocL: "manus", vocG: "cheir, chir-", deu: "die Hand" },
    { typ: "GL", vocL: "medicamentum", vocG: "pharmakon", deu: "das Heilmittel" },
    { typ: "GL", vocL: "medulla", vocG: "myelos", deu: "das Mark" },
    { typ: "GL", vocL: "musculus", vocG: "mys", deu: "der Muskel" },
    { typ: "GL", vocL: "nasus", vocG: "rhis, rhin-", deu: "die Nase" },
    { typ: "GL", vocL: "nervus", vocG: "neuron", deu: "der Nerv" },
    { typ: "GL", vocL: "nucleus", vocG: "karyon", deu: "der Kern" },
    { typ: "GL", vocL: "oculus", vocG: "ophthalmos", deu: "das Auge" },
    { typ: "GL", vocL: "omentum", vocG: "epiploon", deu: "das Netz" },
    { typ: "GL", vocL: "os, oris", vocG: "stoma", deu: "der Mund" },
    { typ: "GL", vocL: "os, ossis", vocG: "osteon", deu: "der Knochen" },
    { typ: "GL", vocL: "ovarium", vocG: "oophoron", deu: "der Eierstock" },
    { typ: "GL", vocL: "palpebra", vocG: "blepharon", deu: "das Augenlid" },
    { typ: "GL", vocL: "pectus", vocG: "thorax, stethos", deu: "die Brust" },
    { typ: "GL", vocL: "pes", vocG: "pous, ", deu: "pod- der Fuß" },
    { typ: "GL", vocL: "pulmo", vocG: "pneumon", deu: "die Lunge" },
    { typ: "GL", vocL: "pupilla", vocG: "kore", deu: "die Pupille" },
    { typ: "GL", vocL: "ren", vocG: "nephron", deu: "die Niere" },
    { typ: "GL", vocL: "sanguis", vocG: "haima, häm-, hämat-", deu: "das Blut" },
    { typ: "GL", vocL: "sudor", vocG: "hidros", deu: "der Schweiß" },
    { typ: "GL", vocL: "testis", vocG: "orchis", deu: "der Hoden" },
    { typ: "GL", vocL: "tuba(uterina)", vocG: "salpinx, salping-", deu: "der Eileiter" },
    { typ: "GL", vocL: "tumor", vocG: "onkos", deu: "das Geschwür" },
    { typ: "GL", vocL: "uterus", vocG: "metra, hystera", deu: "die Gebärmutter" },
    { typ: "GL", vocL: "vagina", vocG: "kolpos", deu: "die Scheide" },
    { typ: "GL", vocL: "vas", vocG: "angion", deu: "das Gefäß" },
    { typ: "GL", vocL: "vena", vocG: "phlebs", deu: "die Vene" },
    { typ: "GL", vocL: "venter", vocG: "lapara", deu: "der Magen, Bauch" },
    { typ: "GL", vocL: "ventriculus", vocG: "gaster, gastr-", deu: "der Magen" },
    { typ: "GL", vocL: "vertebra", vocG: "spondylos", deu: "der Wirbel" },
    { typ: "GL", vocL: "vesica (uterina)", vocG: "kystis", deu: "die Harnblase, Blase" },
    { typ: "GL", vocL: "vir", vocG: "aner, ", deu: "andr- der Mann" },
    { typ: "GL", vocL: "viscera", vocG: "splanchnon", deu: "der Darm" },
    {
        typ: "M",
        voc: "comperative",
        deu: `
stem +
      m/f   n
n sg  ior   us
g sg  ioris oris
n pl  iores ora
g pl  iorum orum`
    },
    {
        typ: "M",
        voc: "superlative",
        deu: `
 stem +
      m         f         n
n sg  issimus   issima    issimum
g sg  issimi    issimae   issimi
n pl  issimi    issimae   issima
g pl  issimorum issimarum issimorum`
    }
];

export default data;
